### ISSUE TITLE
gem is not published?

### ISSUE THREAD

**Issue by TSMMark** [filewatcher/filewatcher-spinner#48]
> Could not find gem 'filewatcher-spinner' in any of the gem sources listed in your Gemfile.

https://rubygems.org/gems/filewatcher-spinner 404

**Comment by AlexWayfer** [comment]
Now it's released as beta-version: https://rubygems.org/gems/filewatcher-spinner

We'll wait for stable `filewatcher 2.0` version before make it stable.

Notice: for locking at beta-version you have to specified them explicitly.

I'm going to leave this issue open until a stable release. Thank you for notification.

**Comment by AlexWayfer** [comment]
Now it's published. :tada:
